#!/bin/bash

# Definition der Optionen
OPTS="  Sperren\n  Abmelden\n  Schlafen\n  Neustarten\n  Ausschalten"

PICK=$(echo -e "$OPTS" | wofi --dmenu \
    --no-actions \
    --width 350 \
    --height 280 \
    --cache-file /dev/null \
    --style ~/.config/wofi/style.css \
    --prompt "System" \
    --insensitive)

ACTION=$(echo "$PICK" | awk '{print $NF}' | tr '[:upper:]' '[:lower:]')

echo $ACTION

case $ACTION in
    sperren)
        swaylock -f
        ;;
    abmelden)
        swaymsg exit
        ;;
    schlafen)
        systemctl suspend
        ;;
    neustarten)
        systemctl reboot --no-wall
        ;;
    ausschalten)
        systemctl poweroff --no-wall
        ;;
esac
