#!/bin/bash

# Definition der Optionen
OPTS="  Sperren\n  Abmelden\n  Schlafen\n  Neustarten\n  Ausschalten"

PICK=$(echo -e "$OPTS" | wofi --dmenu \
    --no-actions \
    --width 350 \
    --height 280 \
    --cache-file /dev/null \
    --style ~/.config/wofi/style.css \
    --prompt "System")

ACTION=$(echo "$PICK" | awk '{print $NF}')

case $ACTION in
    Sperren)
        swaylock -f
        ;;
    Abmelden)
        swaymsg exit
        ;;
    Schlafen)
        systemctl suspend
        ;;
    Neustarten)
        systemctl reboot --no-wall
        ;;
    Ausschalten)
        systemctl poweroff --no-wall
        ;;
esac
